# Generated by Django 5.2.6 on 2026-05-18 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ERRO', 'Erro / Sistema fora do ar'), ('DUVIDA', 'Dúvida de Uso'), ('MELHORIA', 'Nova Funcionalidade / Melhoria')], default='DUVIDA', max_length=20)),
                ('descricao', models.TextField(verbose_name='O que precisa ser feito?')),
                ('justificativa', models.TextField(verbose_name='Por que isso é necessário?')),
                ('urgencia', models.CharField(blank=True, choices=[('BAIXA', 'Baixa (Quando der tempo)'), ('MEDIA', 'Média (No fluxo normal)'), ('ALTA', 'Alta (Prioridade da semana)'), ('CRITICA', 'Crítica (Pare tudo e resolva)')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto (Aguardando Dev)'), ('AGENDADO', 'Agendado'), ('ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=15)),
                ('data_agendada', models.DateTimeField(blank=True, null=True, verbose_name='Dia e hora para execução')),
                ('resposta_dev', models.TextField(blank=True, null=True, verbose_name='Sua resposta para o setor')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='chamados abertos')),
            ],
        ),
    ]
