# Generated by Django 5.2.6 on 2025-09-04 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteIntegrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('representante_legal', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InstituicaoEnsino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
                ('representante_legal', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ParteConcedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('representante_legal', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Estagiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('endereco', models.CharField(max_length=250)),
                ('bairro', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=9)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(default='ENSINO MÉDIO', max_length=100)),
                ('ano_periodo', models.CharField(help_text='Ex: 2° Ano', max_length=100)),
                ('instituicao_ensino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.instituicaoensino')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField()),
                ('data_termino_prevista', models.DateField()),
                ('horario_estagio', models.CharField(max_length=100)),
                ('atividades', models.TextField()),
                ('setor', models.CharField(max_length=100)),
                ('supervisor_nome', models.CharField(max_length=100)),
                ('numero_apolice_seguro', models.CharField(max_length=50)),
                ('agente_integrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.agenteintegrador')),
                ('estagiario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.estagiario')),
                ('parte_concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.parteconcedente')),
            ],
        ),
        migrations.CreateModel(
            name='Rescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rescisao', models.DateField()),
                ('motivo', models.TextField()),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estagios.contrato')),
            ],
        ),
    ]
