# Generated by Django 5.2.6 on 2025-09-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor_bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
