# Generated by Django 5.2.6 on 2025-09-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0002_contrato_valor_bolsa'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='jornada_estagio',
            field=models.CharField(blank=True, help_text='de segunda a domingo com uma folga na semana e 15 minutos de pausa', max_length=150, null=True),
        ),
    ]
