# Generated by Django 5.2.6 on 2025-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0003_contrato_jornada_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_contrato',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
