# Generated by Django 5.2.6 on 2025-09-12 14:30

from django.db import migrations
from django.utils import timezone


def preencher_numeros(apps, schema_editor):
    Contrato = apps.get_model('estagios', 'Contrato')

    for contrato in Contrato.objects.all():
        if not contrato.numero_contrato:
            ano = contrato.data_inicio.year if contrato.data_inicio else timezone.now().year
            contrato.numero_contrato = f'CT-{ano}-{contrato.id:04d}'
            contrato.save(update_fields=['numero_contrato'])


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0004_alter_contrato_numero_contrato'),
    ]

    operations = [
        migrations.RunPython(preencher_numeros),
    ]
