# Generated by Django 5.2.6 on 2025-09-19 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0005_preenche_numeros_contrato'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenteintegrador',
            options={'verbose_name': 'Agente Integrador', 'verbose_name_plural': 'Agentes Integradores'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='estagiario',
            options={'verbose_name': 'Estagiário', 'verbose_name_plural': 'Estagiários'},
        ),
        migrations.AlterModelOptions(
            name='instituicaoensino',
            options={'verbose_name': 'Instituição de Ensino', 'verbose_name_plural': 'Instituições de Ensino'},
        ),
        migrations.AlterModelOptions(
            name='parteconcedente',
            options={'verbose_name': 'Parte Concedente', 'verbose_name_plural': 'Partes Concedentes'},
        ),
        migrations.AlterModelOptions(
            name='rescisao',
            options={'verbose_name': 'Rescisão', 'verbose_name_plural': 'Rescisões'},
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=50)),
                ('rg', models.CharField(max_length=9, unique=True)),
                ('anexar_rg', models.FileField(blank=True, null=True, upload_to='documentos_candidatos/rg/%Y%/%m/%d/', verbose_name='Anexar RG')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('anexar_cpf', models.FileField(blank=True, null=True, upload_to='documentos_candidatos/cpf/%Y%/%m/%d/', verbose_name='Anexar CPF')),
                ('data_nascimento', models.DateField()),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], max_length=1)),
                ('tem_filhos', models.BooleanField(default=False, help_text='Tem filhos?')),
                ('filhos_detalhes', models.CharField(blank=True, help_text='Quais as idades?', max_length=150, null=True)),
                ('celular', models.CharField(help_text='11911112222', max_length=11, unique=True)),
                ('celular2', models.CharField(blank=True, help_text='Opcional', max_length=11, null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('rede_social', models.CharField(blank=True, help_text='Instagram ou Facebook', max_length=100, null=True)),
                ('cep', models.CharField(blank=True, help_text='00000-000', max_length=9, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=50, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=2)),
                ('habilitacao', models.CharField(choices=[('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categorias A e B')], max_length=2)),
                ('fumante', models.BooleanField(default=False, help_text='É fumante?')),
                ('religiao', models.CharField(blank=True, help_text='Possui alguma religião? Se sim, qual?', max_length=100, null=True)),
                ('conheceu_agencia', models.CharField(help_text='Como conheceu a agência?', max_length=100)),
                ('escolaridade', models.CharField(choices=[('EM', 'Ensino Médio'), ('EMT', 'Ensino Médio Técnico'), ('ES', 'Ensino Superior'), ('EJA', 'Educação de Jovens e Adultos')], max_length=3)),
                ('curso', models.CharField(blank=True, help_text='Nome do curso', max_length=70, null=True)),
                ('periodo', models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral')], max_length=1)),
                ('serie_semestre', models.CharField(help_text='2° semestre / 3°ano', max_length=50)),
                ('data_termino', models.DateField(help_text='Quando o curso / escola acaba?')),
                ('carteirinha', models.BooleanField(default=False, help_text='Possui carteirinha de ônibus?')),
                ('curso_extracurricular', models.CharField(help_text='Sim, de informática das 08h as 10h / Não', max_length=200)),
                ('anexar_declaracao', models.FileField(blank=True, null=True, upload_to='documentos_candidatos/declaracao/%Y%/%m/%d/')),
                ('trabalho', models.CharField(choices=[('CR', 'Sim, com registro'), ('SR', 'Sim, sem registro'), ('N', 'Nao')], max_length=2)),
                ('disponibilidade_final_semana', models.BooleanField(default=False, help_text='Pode trabalhar de final de semana?')),
                ('microsoft_365', models.CharField(choices=[('SC', 'Sem conhecimento'), ('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], help_text='Nível de conhecimento do pacote office', max_length=2)),
                ('experiencia_profissional', models.CharField(blank=True, help_text='Empresa X, 08/23-03/25, atividades que desempenhava', max_length=300, null=True)),
                ('area_interesse', models.CharField(help_text='Qual a sua área de interesse?', max_length=100)),
                ('vaga_pretendida', models.CharField(help_text='Para qual vaga você deseja ser encaminhado(a)?', max_length=100)),
                ('pretensao_salarial', models.DecimalField(decimal_places=2, max_digits=9)),
                ('anexar_curriculo', models.FileField(blank=True, null=True, upload_to='documentos_candidatos/curriculo/%Y/%m/%d/')),
                ('medicamento_constante', models.CharField(help_text='Faz uso de algum medicamento constante?', max_length=100)),
                ('alergia', models.CharField(help_text='Tem alergia a algum medicamento? Se sim, qual?', max_length=100)),
                ('problema_saude', models.CharField(help_text='Tem algum problema de saúde?', max_length=100)),
                ('pcd', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao'), ('PNR', 'Prefiro não responder')], help_text='Você é uma pessoa com deficiência (PCD)?', max_length=3)),
                ('pcd_detalhes', models.CharField(blank=True, help_text='Se sim, qual(is)?', max_length=150, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=70, null=True)),
                ('telefone_pai', models.CharField(blank=True, max_length=11, null=True)),
                ('email_pai', models.EmailField(blank=True, max_length=254, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=70, null=True)),
                ('telefone_mae', models.CharField(blank=True, max_length=11, null=True)),
                ('email_mae', models.EmailField(blank=True, max_length=254, null=True)),
                ('instituicao_ensino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.instituicaoensino')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
    ]
