# Generated by Django 5.2.6 on 2025-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0006_alter_agenteintegrador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='data_termino',
            field=models.DateField(blank=True, help_text='Quando o curso / escola acaba?', null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pretensao_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
