# Generated by Django 5.2.6 on 2025-09-19 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0007_alter_candidato_data_termino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estagiario',
            name='ano_periodo',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='estagiario',
            name='telefone',
        ),
        migrations.AddField(
            model_name='estagiario',
            name='candidato',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='estagios.candidato'),
        ),
    ]
