# Generated by Django 5.2.6 on 2025-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0008_remove_estagiario_ano_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='experiencia_profissional',
            field=models.TextField(blank=True, help_text='Exemplo: Empresa X, 08/23-03/25, atividades que desempenhava', null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilitacao',
            field=models.CharField(choices=[('NP', 'Não possui'), ('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categorias A e B')], max_length=2),
        ),
    ]
