# Generated by Django 5.2.6 on 2025-09-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0009_alter_candidato_experiencia_profissional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='carteirinha',
        ),
        migrations.AddField(
            model_name='candidato',
            name='vale_transporte',
            field=models.CharField(choices=[('T', 'Top'), ('C', 'Cidadão'), ('E', 'Estudante'), ('NT', 'Não tem')], default='E', max_length=2),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pcd',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('PNR', 'Prefiro não responder')], help_text='Você é uma pessoa com deficiência (PCD)?', max_length=3),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='trabalho',
            field=models.CharField(choices=[('CR', 'Sim, com registro'), ('SR', 'Sim, sem registro'), ('N', 'Não')], max_length=2),
        ),
    ]
