# Generated by Django 5.2.6 on 2025-09-30 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0010_remove_candidato_carteirinha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral'), ('E', 'EAD')], max_length=1),
        ),
    ]
