# Generated by Django 5.2.6 on 2025-09-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0011_alter_candidato_periodo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='email_mae',
            new_name='email_responsavel_legal',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='email_pai',
            new_name='email_responsavel_legal2',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='nome_mae',
            new_name='nome_responsavel_legal2',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='telefone_mae',
            new_name='telefone_responsavel_legal',
        ),
        migrations.RenameField(
            model_name='candidato',
            old_name='telefone_pai',
            new_name='telefone_responsavel_legal2',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='nome_pai',
        ),
        migrations.AddField(
            model_name='candidato',
            name='idade_responsavel_legal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='idade_responsavel_legal2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_responsavel_legal',
            field=models.CharField(blank=True, help_text='Pai, mãe ou guardião(ã)', max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='profissao_responsavel_legal',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='profissao_responsavel_legal2',
            field=models.CharField(blank=True, null=True),
        ),
    ]
