# Generated by Django 5.2.6 on 2025-09-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0012_rename_email_mae_candidato_email_responsavel_legal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
