# Generated by Django 5.2.6 on 2025-10-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0013_candidato_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='idade_responsavel_legal',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='idade_responsavel_legal2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='profissao_responsavel_legal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='profissao_responsavel_legal2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
