# Generated by Django 5.2.6 on 2025-10-20 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0016_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='anexar_carteira_trabalho',
            field=models.FileField(blank=True, null=True, upload_to='documentos_candidatos/carteiras_trabalho/%Y%/%m/%d/', verbose_name='Anexar Carteira de Trabalho'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='anexar_reservista',
            field=models.FileField(blank=True, null=True, upload_to='documentos_candidatos/reservistas/%Y%/%m/%d/', verbose_name='Anexar Reservista'),
        ),
        migrations.CreateModel(
            name='CartaEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='cartas_encaminhamento/')),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas', to='estagios.candidato')),
            ],
            options={
                'verbose_name': 'Carta de Encaminhamento',
                'verbose_name_plural': 'Cartas de Encaminhamento',
            },
        ),
    ]
