# Generated by Django 5.2.6 on 2025-10-21 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0018_arquivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='arquivos/'),
        ),
        migrations.AlterField(
            model_name='cartaencaminhamento',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='cartas_encaminhamento/'),
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=120, null=True)),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='empresas/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='estagios.candidato')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
    ]
