# Generated by Django 5.2.6 on 2025-10-21 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0019_candidato_data_cadastro_alter_arquivos_arquivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='arquivos',
        ),
        migrations.AlterField(
            model_name='arquivos',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartaencaminhamento',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DetalhesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivos', models.FileField(blank=True, null=True, upload_to='empresas/')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='estagios.empresa')),
            ],
            options={
                'verbose_name': 'Detalhes Empresa',
                'verbose_name_plural': 'Detalhes Empresas',
            },
        ),
    ]
