# Generated by Django 5.2.6 on 2025-10-23 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0020_remove_empresa_arquivos_alter_arquivos_data_emissao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='restrito',
            field=models.BooleanField(default=False),
        ),
    ]
