# Generated by Django 5.2.6 on 2025-10-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0021_candidato_restrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='nome_da_instituicao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
