# Generated by Django 5.2.6 on 2025-10-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0022_candidato_nome_da_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='nome_da_instituicao',
            field=models.CharField(blank=True, help_text='Caso não esteja na lista', max_length=150, null=True),
        ),
    ]
