# Generated by Django 5.2.6 on 2025-10-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0023_alter_candidato_nome_da_instituicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalhesParteConcedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_pagamento_estagiario', models.IntegerField(blank=True, null=True)),
                ('dia_cobranca_agencia', models.IntegerField(blank=True, null=True)),
                ('dia_fechamento', models.IntegerField(blank=True, null=True)),
                ('mensalidade_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('taxa_cliente', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('parte_concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='estagios.parteconcedente')),
            ],
        ),
    ]
