# Generated by Django 5.2.6 on 2025-11-03 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0024_detalhesparteconcedente'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('CREDITO', 'Crédito'), ('DEBITO', 'Débito')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagiario_nome', models.CharField(max_length=100)),
                ('parte_concedente_nome', models.CharField(max_length=100)),
                ('valor_bolsa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_referencia', models.DateField()),
                ('dias_referencia', models.IntegerField(default=30)),
                ('dias_trabalhados', models.IntegerField(default=22)),
                ('dias_falta', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('beneficio_horario', models.TextField(blank=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagios.contrato')),
            ],
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='estagios.recibo')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.tipoevento')),
            ],
        ),
    ]
