# Generated by Django 5.2.6 on 2025-11-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0025_tipoevento_recibo_lancamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='data_referencia',
            field=models.DateField(help_text='Deve ser o 1º dia do mês de referência'),
        ),
        migrations.AlterField(
            model_name='recibo',
            name='dias_trabalhados',
            field=models.IntegerField(),
        ),
    ]
