# Generated by Django 5.2.6 on 2025-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0026_alter_recibo_data_referencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero_apolice_seguro',
            field=models.CharField(default='363787', max_length=50),
        ),
    ]
