# Generated by Django 5.2.6 on 2025-11-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0027_alter_contrato_numero_apolice_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteconcedente',
            name='local_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
