# Generated by Django 5.2.6 on 2025-11-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0028_parteconcedente_local_trabalho'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoRescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Motivo da rescisão',
                'verbose_name_plural': 'Motivos da rescisão',
            },
        ),
        migrations.AlterField(
            model_name='rescisao',
            name='motivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.motivorescisao'),
        ),
    ]
