# Generated by Django 5.2.6 on 2025-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0029_motivorescisao_alter_rescisao_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='app_escolar',
            field=models.CharField(blank=True, help_text='Nome do aplicativo da escola/faculdade caso tenha', max_length=50, verbose_name='Aplicativo da escola/faculdade'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
