# Generated by Django 5.2.6 on 2025-11-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0030_candidato_app_escolar_alter_candidato_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='app_escolar',
            field=models.CharField(blank=True, help_text='Não / Nome do aplicativo da escola/faculdade caso tenha', max_length=50, verbose_name='Aplicativo da escola/faculdade'),
        ),
    ]
