# Generated by Django 5.2.6 on 2025-11-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0031_alter_candidato_app_escolar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboRescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estagiario_nome', models.CharField(max_length=100)),
                ('parte_concedente_nome', models.CharField(max_length=100)),
                ('valor_bolsa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('data_rescisao', models.DateField()),
                ('data_pagamento', models.DateField()),
                ('saldo_salario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recesso_remunerado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aviso_previo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adiantamentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('outros_descontos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_debitos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estagios.contrato')),
                ('motivo_rescisao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='estagios.motivorescisao')),
            ],
        ),
    ]
