# Generated by Django 5.2.6 on 2025-11-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0032_reciborescisao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciborescisao',
            name='adiantamentos',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='aviso_previo',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='outros_descontos',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='recesso_remunerado',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='saldo_salario',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='total_creditos',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='total_debitos',
        ),
        migrations.RemoveField(
            model_name='reciborescisao',
            name='valor_liquido',
        ),
        migrations.AddField(
            model_name='reciborescisao',
            name='dias_recesso_devidos',
            field=models.IntegerField(default=0, help_text='Dias de recesso devidos'),
        ),
        migrations.AddField(
            model_name='reciborescisao',
            name='dias_trabalhados_mes',
            field=models.IntegerField(default=0, help_text='Dias trabalhados no mês da rescisão'),
        ),
    ]
