# Generated by Django 5.2.6 on 2025-11-19 14:27

from django.db import migrations
from django.utils import timezone


def preencher_data_criacao(apps, schema_editor):
    Contrato = apps.get_model('estagios', 'Contrato')
    for contrato in Contrato.objects.all():
        contrato.data_criacao = timezone.now()
        contrato.save()


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0033_remove_reciborescisao_adiantamentos_and_more'),
    ]

    operations = [
        migrations.RunPython(preencher_data_criacao),
    ]
