# Generated by Django 5.2.6 on 2025-11-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0034_auto_20251119_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_criacao',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
