# Generated by Django 5.2.6 on 2025-11-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0035_contrato_data_criacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reciborescisao',
            options={'verbose_name': 'Recibo de Rescisão', 'verbose_name_plural': 'Recibos de Rescisão'},
        ),
        migrations.AddField(
            model_name='lancamento',
            name='recibo_rescisao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_rescisao', to='estagios.reciborescisao'),
        ),
    ]
