# Generated by Django 5.2.6 on 2025-11-20 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0036_alter_reciborescisao_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lancamento',
            name='recibo_rescisao',
        ),
        migrations.CreateModel(
            name='LancamentoRescisao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recibo_rescisao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos_rescisao', to='estagios.reciborescisao')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.tipoevento')),
            ],
        ),
    ]
