# Generated by Django 5.2.6 on 2025-11-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0037_remove_lancamento_recibo_rescisao_lancamentorescisao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamentorescisao',
            options={'verbose_name': 'Lançamento de rescisão', 'verbose_name_plural': 'Lançamentos de rescisão'},
        ),
    ]
