# Generated by Django 5.2.6 on 2025-11-24 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0038_alter_lancamentorescisao_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_dono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do(a) dono(a)')),
                ('documentos_dono', models.FileField(blank=True, help_text='RG, CPF ou CNH', null=True, upload_to='documentos_dono/gerais/%Y%/%m/%d/', verbose_name='Anexar documento')),
                ('nome_socio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do(a) sócio(a)')),
                ('documentos_socio', models.FileField(blank=True, help_text='RG, CPF ou CNH', null=True, upload_to='documentos_socio/gerais/%Y%/%m/%d/', verbose_name='Anexar documento')),
                ('nome_resp_rh', models.CharField(max_length=100, verbose_name='Nome do(a) responsável do RH')),
                ('numero_resp_rh', models.CharField(help_text='Número do telefone com DDD e sem traços', max_length=11, verbose_name='Número do(a) responsável do RH')),
                ('email_resp_rh', models.EmailField(max_length=254, verbose_name='Email do(a) responsável do RH')),
                ('nome_resp_estagio', models.CharField(max_length=100, verbose_name='Nome do(a) responsável do estágio')),
                ('parte_concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adicionais', to='estagios.parteconcedente')),
            ],
        ),
    ]
