# Generated by Django 5.2.6 on 2025-11-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0039_contratosocial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratosocial',
            options={'verbose_name': 'Contrato Social', 'verbose_name_plural': 'Contratos Sociais'},
        ),
        migrations.AddField(
            model_name='parteconcedente',
            name='ramo_atividade',
            field=models.CharField(max_length=200, null=True, verbose_name='Ramo de atividade'),
        ),
    ]
