# Generated by Django 5.2.6 on 2025-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0040_alter_contratosocial_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_dono',
            field=models.CharField(null=True, verbose_name='CPF do(a) dono(a)'),
        ),
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_socio',
            field=models.FileField(null=True, upload_to='', verbose_name='CPF do(a) sócio(a)'),
        ),
    ]
