# Generated by Django 5.2.6 on 2025-11-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0042_alter_contratosocial_documentos_dono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_dono',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='CPF do(a) dono(a)'),
        ),
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_socio',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='', verbose_name='CPF do(a) sócio(a)'),
        ),
    ]
