# Generated by Django 5.2.6 on 2025-11-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0043_alter_contratosocial_documentos_dono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='vaga_pretendida',
            field=models.CharField(editable=False, help_text='Para qual vaga você deseja ser encaminhado(a)?', max_length=100),
        ),
    ]
