# Generated by Django 5.2.6 on 2025-11-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0044_alter_candidato_vaga_pretendida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='area_interesse',
            field=models.CharField(help_text='Qual a sua área de interesse?', max_length=100, verbose_name='Área de interesse'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cep',
            field=models.CharField(blank=True, help_text='00000-000', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='conheceu_agencia',
            field=models.CharField(max_length=100, verbose_name='Como conheceu a agência?'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_nascimento',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Quando o curso / escola acaba?'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilitacao',
            field=models.CharField(choices=[('NP', 'Não possui'), ('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categorias A e B')], max_length=2, verbose_name='Habilitação'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='numero',
            field=models.CharField(max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='periodo',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite'), ('I', 'Integral'), ('E', 'EAD')], max_length=1, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='religiao',
            field=models.CharField(blank=True, help_text='Possui alguma religião? Se sim, qual?', max_length=100, null=True, verbose_name='Religião'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, max_length=9, unique=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='serie_semestre',
            field=models.CharField(help_text='2° semestre / 3°ano', max_length=50, verbose_name='Série ou Semestre'),
        ),
    ]
