# Generated by Django 5.2.6 on 2025-11-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0045_alter_candidato_area_interesse_alter_candidato_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratosocial',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
