# Generated by Django 5.2.6 on 2025-11-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0046_contratosocial_data_cadastro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aditivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('contrato_social', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrato_social', to='estagios.contratosocial')),
            ],
            options={
                'verbose_name': 'Aditivo',
                'verbose_name_plural': 'Aditivos',
            },
        ),
    ]
