# Generated by Django 5.2.6 on 2025-11-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0047_aditivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteconcedente',
            name='nome',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='parteconcedente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
