# Generated by Django 5.2.6 on 2025-11-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0048_parteconcedente_nome_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aditivo',
            options={'verbose_name': 'Aditivo Contratual', 'verbose_name_plural': 'Aditivos Contratuais'},
        ),
        migrations.AlterModelOptions(
            name='contratosocial',
            options={'verbose_name': 'Contrato Empresa', 'verbose_name_plural': 'Contratos para Empresas'},
        ),
    ]
