# Generated by Django 5.2.6 on 2025-11-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0049_alter_aditivo_options_alter_contratosocial_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='ano_semestre',
            field=models.CharField(choices=[('1A', '1° Ano'), ('2A', '2° Ano'), ('3A', '3° Ano'), ('4A', '4° Ano'), ('1S', '1° Semestre'), ('2S', '2° Semestre'), ('3S', '3° Semestre'), ('4S', '4° Semestre'), ('5S', '5° Semestre'), ('6S', '6° Semestre'), ('7S', '7° Semestre'), ('8S', '8° Semestre'), ('9S', '9° Semestre'), ('1OS', '10° Semestre'), ('11S', '11° Semestre'), ('12S', '12° Semestre')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='serie_semestre',
            field=models.CharField(editable=False, help_text='2° semestre / 3°ano', max_length=50, verbose_name='Série ou Semestre'),
        ),
    ]
