# Generated by Django 5.2.6 on 2025-11-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0052_alter_candidato_ano_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_socio',
            field=models.CharField(blank=True, null=True, unique=True, verbose_name='CPF do(a) sócio(a)'),
        ),
    ]
