# Generated by Django 5.2.6 on 2025-11-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0053_alter_contratosocial_documentos_socio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(help_text='Somente números', max_length=11, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, help_text='Somente números', max_length=9, unique=True, verbose_name='RG'),
        ),
    ]
