# Generated by Django 5.2.6 on 2025-12-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0054_alter_candidato_cpf_alter_candidato_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='restrito',
            field=models.BooleanField(default=True),
        ),
    ]
