# Generated by Django 5.2.6 on 2025-12-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0055_alter_candidato_restrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='restrito',
            field=models.BooleanField(default=False),
        ),
    ]
