# Generated by Django 5.2.6 on 2025-12-01 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0056_alter_candidato_restrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='instituicao_ensino',
            field=models.ForeignKey(default='Não está na lista', on_delete=django.db.models.deletion.PROTECT, to='estagios.instituicaoensino'),
        ),
    ]
