# Generated by Django 5.2.6 on 2025-12-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0057_alter_candidato_instituicao_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='instituicao_ensino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.instituicaoensino'),
        ),
    ]
