# Generated by Django 5.2.6 on 2025-12-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0058_alter_candidato_instituicao_ensino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='horario_estagio',
            field=models.CharField(editable=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='jornada_estagio',
            field=models.TextField(null=True),
        ),
    ]
