# Generated by Django 5.2.6 on 2025-12-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0059_alter_contrato_horario_estagio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_termino_prevista',
            field=models.DateField(verbose_name='Data de término prevista'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='jornada_estagio',
            field=models.TextField(null=True, verbose_name='Jornada de estágio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='supervisor_nome',
            field=models.CharField(max_length=100, verbose_name='Nome do(a) supervisor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_bolsa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Valor da bolsa'),
        ),
    ]
