# Generated by Django 5.2.6 on 2025-12-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0060_alter_contrato_data_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriterioExclusao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Critério de Exclusão',
                'verbose_name_plural': 'Critérios de Exclusão',
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='criterio_exclusao',
            field=models.ManyToManyField(blank=True, null=True, to='estagios.criterioexclusao', verbose_name='Critérios de Exclusão'),
        ),
    ]
