# Generated by Django 5.2.6 on 2025-12-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0062_alter_candidato_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='criterio_exclusao',
            field=models.ManyToManyField(blank=True, to='estagios.criterioexclusao', verbose_name='Critérios de Exclusão'),
        ),
    ]
