# Generated by Django 5.2.6 on 2025-12-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0063_alter_candidato_criterio_exclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, help_text='Somente números, campo não necessário caso você tenha o CIN', max_length=9, null=True, unique=True, verbose_name='RG'),
        ),
    ]
