# Generated by Django 5.2.6 on 2025-12-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0064_alter_candidato_rg'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('plano', models.CharField(choices=[('P', 'Plus'), ('S', 'Sênior')], max_length=1)),
                ('parte_concedente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.parteconcedente')),
            ],
            options={
                'verbose_name': 'Contrato R&S - Aceite',
                'verbose_name_plural': 'Contratos R&S - Aceite',
            },
        ),
    ]
