# Generated by Django 5.2.6 on 2025-12-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0065_contratoaceite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratoaceite',
            name='salario',
        ),
        migrations.RemoveField(
            model_name='contratoaceite',
            name='vaga',
        ),
        migrations.CreateModel(
            name='DetalhesContratoAceite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('vaga', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contrato_aceite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estagios.contratoaceite')),
            ],
        ),
    ]
