# Generated by Django 5.2.6 on 2025-12-03 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0066_remove_contratoaceite_salario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalhescontratoaceite',
            options={'verbose_name': 'Detalhe do Contrato R&S', 'verbose_name_plural': 'Detalhes dos Contratos R&S'},
        ),
    ]
