# Generated by Django 5.2.6 on 2025-12-03 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0067_alter_detalhescontratoaceite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalhescontratoaceite',
            name='contrato_aceite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalhes', to='estagios.contratoaceite'),
        ),
    ]
