# Generated by Django 5.2.6 on 2025-12-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0068_alter_detalhescontratoaceite_contrato_aceite'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoaceite',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default='2025-01-01'),
            preserve_default=False,
        ),
    ]
