# Generated by Django 5.2.6 on 2025-12-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0069_contratoaceite_data_cadastro'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='nome_medicamento',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do(s) medicamento(s)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='usa_medicamento',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Faz uso de algum medicamento?'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='trabalho',
            field=models.CharField(choices=[('CR', 'Sim, com registro'), ('SR', 'Sim, sem registro'), ('N', 'Não'), ('F', 'Freelancer')], max_length=2),
        ),
    ]
