# Generated by Django 5.2.6 on 2025-12-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0071_auto_20251209_1115'),
        ('estagios', '0072_auto_20251209_1128'),
    ]

    operations = [
    ]
