# Generated by Django 5.2.6 on 2025-12-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0073_merge_0071_auto_20251209_1115_0072_auto_20251209_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='nome_alergia',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Alergia a qual(is) medicamento(s)?'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tem_alergia',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Tem alergia a algum medicamento?'),
        ),
    ]
