# Generated by Django 5.2.6 on 2025-12-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0075_auto_20251209_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='alergia',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='medicamento_constante',
        ),
    ]
