# Generated by Django 5.2.6 on 2025-12-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0076_remove_candidato_alergia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='nome_problema_saude',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nome do(s) problema(s)'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='tem_problema_saude',
            field=models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Tem algum problema de saúde?'),
        ),
    ]
