# Generated by Django 5.2.6 on 2025-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0078_auto_20251209_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='problema_saude',
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.CharField(blank=True, help_text='Nome do curso, caso esteja na faculdade', max_length=70, null=True),
        ),
    ]
