# Generated by Django 5.2.6 on 2025-12-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0079_remove_candidato_problema_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='trabalho',
            field=models.CharField(choices=[('CR', 'Sim, com registro'), ('SR', 'Sim, sem registro'), ('N', 'Não'), ('F', 'Freelancer')], max_length=2, verbose_name='Já trabalhou?'),
        ),
    ]
