# Generated by Django 5.2.6 on 2025-12-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0080_alter_candidato_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='trabalho',
            field=models.CharField(choices=[('CR', 'Sim, com registro (CLT)'), ('SR', 'Sim, sem registro'), ('N', 'Não'), ('F', 'Freelancer'), ('E', 'Estágio')], max_length=2, verbose_name='Já trabalhou?'),
        ),
    ]
