# Generated by Django 5.2.6 on 2026-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0081_alter_candidato_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números', max_length=11, unique=True, verbose_name='CPF'),
        ),
    ]
