# Generated by Django 5.2.6 on 2026-01-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0082_alter_candidato_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números', max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
