# Generated by Django 5.2.6 on 2026-01-12 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0083_alter_candidato_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('EM', 'Ensino Médio'), ('EMT', 'Ensino Médio Técnico'), ('ESI', 'Ensino Superior Incompleto'), ('ES', 'Ensino Superior'), ('EJA', 'Educação de Jovens e Adultos')], max_length=3),
        ),
    ]
