# Generated by Django 5.2.6 on 2026-01-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0084_alter_candidato_escolaridade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='rg',
            field=models.CharField(blank=True, help_text='Somente números, campo não necessário caso você tenha o CIN', max_length=12, null=True, unique=True, verbose_name='RG'),
        ),
    ]
