# Generated by Django 5.2.6 on 2026-01-16 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0085_alter_candidato_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='assinatura',
            field=models.BooleanField(default=False),
        ),
    ]
