# Generated by Django 5.2.6 on 2026-01-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0086_contrato_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='stand_by',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='trabalhando',
            field=models.BooleanField(default=False),
        ),
    ]
