# Generated by Django 5.2.6 on 2026-02-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0087_candidato_stand_by_candidato_trabalhando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='trabalhando',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
