# Generated by Django 5.2.6 on 2026-02-02 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0088_alter_candidato_trabalhando'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_rescisao',
            field=models.DateField(blank=True, help_text='Preencher apenas se o contrato tiver sidoencerrado antes do prazo', null=True, verbose_name='Data de Rescisão'),
        ),
    ]
