# Generated by Django 5.2.6 on 2026-02-03 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0089_contrato_data_rescisao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('EM', 'Ensino Médio'), ('EMC', 'Ensino Médio Completo'), ('EMT', 'Ensino Médio Técnico'), ('ESI', 'Ensino Superior Incompleto'), ('ES', 'Ensino Superior'), ('EJA', 'Educação de Jovens e Adultos')], max_length=3),
        ),
    ]
