# Generated by Django 5.2.6 on 2026-02-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0090_alter_candidato_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroContatoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome ou Razão Social da empresa')),
                ('contato', models.CharField(choices=[('T', 'Telefone'), ('E', 'Email'), ('W', 'WhatsApp')], verbose_name='De que forma se deu o contato?')),
                ('numero_email', models.CharField(max_length=150, verbose_name='Número ou email da empresa')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Data do contato')),
            ],
            options={
                'verbose_name': 'Registro de contato da empresa',
                'verbose_name_plural': 'Registros de contato das empresas',
            },
        ),
    ]
