# Generated by Django 5.2.6 on 2026-02-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0092_alter_candidato_ano_semestre_alter_candidato_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='desistiu',
            field=models.BooleanField(default=False, verbose_name='Desistiu'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='encaminhado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nao_compareceu',
            field=models.BooleanField(default=False, verbose_name='Não Compareceu'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='reprovado',
            field=models.BooleanField(default=False),
        ),
    ]
