# Generated by Django 5.2.6 on 2026-03-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0093_candidato_aprovado_candidato_desistiu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='em_processo',
            field=models.BooleanField(default=False),
        ),
    ]
