# Generated by Django 5.2.6 on 2026-03-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0094_candidato_em_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='rede_social',
            field=models.CharField(blank=True, help_text='Escreva "Não tenho" caso não possua', max_length=100, null=True),
        ),
    ]
