# Generated by Django 5.2.6 on 2026-03-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0095_alter_candidato_rede_social'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular2',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
    ]
