# Generated by Django 5.2.6 on 2026-03-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0096_alter_candidato_celular2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chamados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_empresa', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('numero', models.CharField(max_length=11, verbose_name='Telefone para contato')),
                ('numero2', models.CharField(max_length=11, verbose_name='Segundo telefone para contato')),
                ('observacoes', models.TextField()),
                ('data_contato', models.DateField()),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
