# Generated by Django 5.2.6 on 2026-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0097_chamados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='observacoes',
            field=models.TextField(verbose_name='Observações'),
        ),
    ]
