# Generated by Django 5.2.6 on 2026-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0098_alter_chamados_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamados',
            name='numero2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Segundo telefone para contato'),
        ),
    ]
