# Generated by Django 5.2.6 on 2026-03-19 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0099_alter_chamados_numero2'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamados',
            name='cnpj',
            field=models.CharField(default='00.000.000/0000-00', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chamados',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos_empresas/assinados/%Y%/%m/%d/', verbose_name='Anexar contrato assinado'),
        ),
        migrations.AddField(
            model_name='chamados',
            name='contrato_assinado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chamados',
            name='proposta_enviada',
            field=models.BooleanField(default=False),
        ),
    ]
