# Generated by Django 5.2.6 on 2026-03-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0100_chamados_cnpj_chamados_contrato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamados',
            options={'verbose_name': 'Chamado', 'verbose_name_plural': 'Chamados'},
        ),
        migrations.AddField(
            model_name='candidato',
            name='idade_conjuge',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='nome_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do(a) cônjuge'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='profissao_conjuge',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
