# Generated by Django 5.2.6 on 2026-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0101_alter_chamados_options_candidato_idade_conjuge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('EM', 'Ensino Médio'), ('EMC', 'Ensino Médio Completo'), ('EMT', 'Ensino Médio Técnico'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Cursando'), ('ES', 'Ensino Superior'), ('EJA', 'Educação de Jovens e Adultos')], max_length=3),
        ),
    ]
