# Generated by Django 5.2.6 on 2026-03-30 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0102_alter_candidato_escolaridade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Vaga')),
                ('descricao', models.TextField(verbose_name='Descrição das Atividades')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='Requisitos da Vaga')),
                ('tipo_vaga', models.CharField(choices=[('E', 'Estágio'), ('C', 'CLT'), ('P', 'PJ'), ('J', 'Jovem Aprendiz')], default='E', max_length=1)),
                ('status', models.CharField(choices=[('A', 'Aberta'), ('F', 'Fechada'), ('C', 'Cancelada'), ('S', 'Suspensa'), ('R', 'Reaberta')], default='A', max_length=1)),
                ('quantidade_vagas', models.PositiveIntegerField(default=1)),
                ('salario_bolsa', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Salário / Bolsa Auxílio')),
                ('beneficios', models.TextField(blank=True, null=True)),
                ('horario', models.CharField(blank=True, max_length=150, null=True)),
                ('local_trabalho', models.CharField(blank=True, help_text='Ex: Híbrido, Remoto, ou Endereço físico', max_length=200, null=True)),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='estagios.parteconcedente')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
            },
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_candidatura', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('N', 'Nova'), ('A', 'Em Análise'), ('E', 'Entrevista'), ('AP', 'Aprovada'), ('R', 'Reprovada')], default='N', max_length=2)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minhas_candidaturas', to='estagios.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='estagios.vaga')),
            ],
            options={
                'verbose_name': 'Candidatura',
                'verbose_name_plural': 'Candidaturas',
                'unique_together': {('vaga', 'candidato')},
            },
        ),
    ]
