# Generated by Django 5.2.6 on 2026-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0103_vaga_candidatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='empresas/documentos/'),
        ),
    ]
