# Generated by Django 5.2.6 on 2026-04-06 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0104_empresa_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoaceite',
            name='empresa_cnpj_documento',
            field=models.CharField(blank=True, help_text='CNPJ que aparecerá no PDF', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contratoaceite',
            name='empresa_nome_documento',
            field=models.CharField(blank=True, help_text='Nome que aparecerá no PDF', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contratoaceite',
            name='observacoes_adicionais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
