# Generated by Django 5.2.6 on 2026-04-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0105_contratoaceite_empresa_cnpj_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoaceite',
            name='taxa_honorarios',
            field=models.CharField(blank=True, help_text='Ex: 50% (cinquenta por cento)', max_length=100, null=True),
        ),
    ]
