# Generated by Django 5.2.6 on 2026-04-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0106_contratoaceite_taxa_honorarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(blank=True, help_text='Somente números', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
