# Generated by Django 5.2.6 on 2026-04-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0107_alter_candidato_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
