# Generated by Django 5.2.6 on 2026-05-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0108_alter_candidato_celular'),
    ]

    operations = [
        migrations.AddField(
            model_name='parteconcedente',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
