# Generated by Django 5.2.6 on 2026-05-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0109_parteconcedente_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
