# Generated by Django 5.2.6 on 2026-05-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0110_vaga_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('A', 'Ambos')], max_length=1, null=True),
        ),
    ]
