# Generated by Django 5.2.6 on 2026-05-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0111_vaga_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='serie_semestre',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Último contato / atualização'),
        ),
    ]
