# Generated by Django 5.2.6 on 2026-06-02 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0112_alter_candidato_serie_semestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='rescindido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidato',
            name='curso_padronizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estagios.curso'),
        ),
    ]
