# Generated by Django 5.2.6 on 2026-06-02 17:34

from django.db import migrations


def padronizar_cursos(apps, schema_editor):
    Candidato = apps.get_model('estagios', 'Candidato')
    Curso = apps.get_model('estagios', 'Curso')

    for candidato in Candidato.objects.all():
        if candidato.curso:
            texto_digitado = candidato.curso.strip()

            if texto_digitado:
                curso_obj, created = Curso.objects.get_or_create(
                    nome__iexact=texto_digitado, defaults={'nome': texto_digitado}
                )
                candidato.curso_padronizado = curso_obj
                candidato.save()

class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0113_curso_candidato_rescindido_and_more'),
    ]

    operations = [
        migrations.RunPython(padronizar_cursos),
    ]
