# Generated by Django 5.2.6 on 2026-06-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0114_auto_20260602_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='escolaridade',
            field=models.CharField(choices=[('EMI', 'Ensino Médio Incompleto'), ('EM', 'Ensino Médio Cursando'), ('EMC', 'Ensino Médio Completo'), ('EMT', 'Ensino Médio Técnico'), ('ESI', 'Ensino Superior Incompleto'), ('ESC', 'Ensino Superior Cursando'), ('ES', 'Ensino Superior Completo'), ('EJA', 'Educação de Jovens e Adultos')], max_length=3),
        ),
    ]
