# Generated by Django 5.2.6 on 2026-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0115_alter_candidato_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='data_edicao',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
