# Generated by Django 5.2.6 on 2026-06-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0117_logacaousuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('criar', 'Criação'), ('editar', 'Edição'), ('deletar', 'Exclusão'), ('visualizar', 'Visualização'), ('exportar', 'Exportação de PDF'), ('outro', 'Outro')], max_length=20)),
                ('descricao', models.TextField()),
                ('objeto_tipo', models.CharField(blank=True, max_length=100)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Ação',
                'verbose_name_plural': 'Registros de Ações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.DeleteModel(
            name='LogAcaoUsuario',
        ),
    ]
