# Generated by Django 5.2.6 on 2026-06-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0118_registroacao_delete_logacaousuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='trabalhando',
            field=models.BooleanField(default=False, verbose_name='Trabalhando'),
        ),
    ]
