# Generated by Django 5.2.6 on 2026-06-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0119_alter_candidato_trabalhando'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='efetivado',
            field=models.BooleanField(default=False),
        ),
    ]
