# Generated by Django 5.2.6 on 2026-07-07 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0120_candidato_efetivado'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivos',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
