# Generated by Django 5.2.6 on 2026-07-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0121_arquivos_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatura',
            name='status',
            field=models.CharField(choices=[('N', 'Nova'), ('A', 'Em Análise'), ('E', 'Entrevista'), ('AP', 'Aprovado'), ('R', 'Reprovado'), ('NC', 'Não Compareceu'), ('D', 'Desistiu'), ('EN', 'Encaminhado')], default='N', max_length=2),
        ),
    ]
