# Generated by Django 5.2.6 on 2026-07-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estagios', '0122_alter_candidatura_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curso',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curso_extracurricular',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='habilitacao',
            field=models.CharField(choices=[('NP', 'Não possui'), ('A', 'Categoria A'), ('B', 'Categoria B'), ('C', 'Categoria C'), ('D', 'Categoria D'), ('E', 'Categoria E'), ('AB', 'Categorias A e B')], default='NP', max_length=2, verbose_name='Habilitação'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='microsoft_365',
            field=models.CharField(choices=[('SC', 'Sem conhecimento'), ('B', 'Básico'), ('I', 'Intermediário'), ('A', 'Avançado')], help_text='Nível de conhecimento do pacote office', max_length=2, verbose_name='Nível do Pacote Office'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='pcd',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não'), ('PNR', 'Prefiro não responder')], default='N', help_text='Você é uma pessoa com deficiência (PCD)?', max_length=3, verbose_name='PCD'),
        ),
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_dono',
            field=models.CharField(blank=True, null=True, verbose_name='CPF do(a) dono(a)'),
        ),
        migrations.AlterField(
            model_name='contratosocial',
            name='documentos_socio',
            field=models.CharField(blank=True, null=True, verbose_name='CPF do(a) sócio(a)'),
        ),
    ]
